### ISSUE TITLE
SitesPerCell.py issue

### ISSUE THREAD

**Issue by kane9530** [cortes-ciriano-lab/SComatic#11]
Hi there,

I am trying to run the SitesPerCell.py script following the documentation in SComaticExample.md, and I am facing the following difficulties:

1. It seems that the documentation for this script in is incomplete in the parameters that are supplied to the argument. 
2. When I run the script as such:
`python3 scripts/SitesPerCell/SitesPerCell.py --bam results/Sample.Epithelial_cells.bam --ref example_data/chr10.fa --infile basecallstep1.calling.step1.tsv`

It appears to complete almost immediately and delete all the files in the current directory. Is this behaviour reproducible on your end?

Best,
Kane

**Comment by Francesc-Muyas** [comment]
Dear user, 
Thanks for using SComatic. Could you briefly answer a few questions to diagnose the problem?

1. Could you let me know if you managed to run the script with the example data? 
2. Could you tell me why you're using our small reference fasta file instead of the one you used for aligning your sample? The provided reference genome is a small fraction of the human genome - chr10 (Hg38 with "chr" prefix ). 
3. Did you check that both reference genomes (your alignment and our reference genome) are compatible and represent the exact same reference genomes?
4. The documentation provided in _SComaticExample.md_ show the example commands used to reproduce the results explained in the manuscript. These commands (recommended) assume some default parameters not shown there. You will find all parameters for this script [here](https://github.com/cortes-ciriano-lab/SComatic/blob/main/docs/OtherFunctionalities.md). 
5. Please be aware that, by default, this script only checks positions in the _basecallstep1.calling.step1.tsv_ that had expression (or coverage) enough for at least two cell types. If this is not your case, please change the _--min_ct1_ and _--min_ct2_ parameters. Importantly, the values for these two parameters should match with parameters used in Step 4.1 (BaseCellCalling.step1.py): _--min_ct1_ ~ _--min_cell_types_  and _--min_ct2_ ~ _--min_cell_types_ . By default (and **strongly recommended**), this value is set to 2. However, if you don't have many cell types with good coverage, you can decrease this cutoff on expenses of much lower performance. 

Thanks again for your interest, 
Fran

**Comment by kane9530** [comment]
Dear Fran,

Thank you for your reply!

1. Currently, i am running the SitesPerCell.py script on the example data, and the reported error arose when trying out the example data. 
2-3. I am using the provided reference because I am running on the example data
4-5 Noted with thanks! 

Best wishes,
Kane
