### ISSUE TITLE
Can SComatic Be Used for snRNA-seq Data? Required Adjustments and Parameters

### ISSUE THREAD

**Issue by lhy329** [cortes-ciriano-lab/SComatic#72]
Hello,

Thank you for developing such a great tool! I am working with single-nucleus RNA-seq (snRNA-seq) data and would like to use SComatic to detect somatic SNVs. Given that snRNA-seq data differs from scRNA-seq due to the high proportion of intronic reads (derived from pre-mRNA), I have a few questions:

Is SComatic suitable for analyzing snRNA-seq data directly, or are there known limitations in its current implementation for such datasets?
What adjustments or preprocessing steps would you recommend when preparing snRNA-seq data for SComatic (e.g., reference genome, read filtering)?
Are there specific parameters in SComatic (e.g., minimum allele fraction, coverage thresholds, etc.) that should be modified to account for the unique characteristics of snRNA-seq data?
Do you recommend excluding intronic regions during preprocessing, or can SComatic handle the intronic reads effectively without increasing false positives?
Thank you for your time and support! I look forward to your insights on applying SComatic to snRNA-seq datasets.

Many thanks!

**Comment by isidroc** [comment]
Hello, thanks for raising this issue. Yes, SComatic does indeed work with snRNAseq data a- in fact, many of the data sets we analysed in the paper were snRNAseq. The sensitivity for mutation detection is higher when using snRNAseq data due to the presence of unspliced transcripts, which allows detection of mutations in introns. I hope this helps. Thanks!
